"""threat intel, soar, ml, reports, notifications, sso, audit, refresh tokens, triage fields

Revision ID: 11c8a454d9b9
Revises: d502c415a9e8
Create Date: 2026-10-01 23:19:44.618662

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c8a454d9b9'
down_revision: Union[str, None] = 'd502c415a9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: every NOT NULL column added to a pre-existing table below carries a
    # `server_default`. Without it, `ALTER TABLE ... ADD COLUMN ... NOT NULL`
    # fails on any database that already has rows -- which is every environment
    # except a fresh one, i.e. exactly the environments a migration is for.
    # The defaults match the model-level defaults so new and migrated rows agree.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_action', ['tenant_id', 'action'], unique=False)
        batch_op.create_index('ix_audit_tenant_created', ['tenant_id', 'created_at'], unique=False)

    op.create_table('compliance_reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('report_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_reports_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_reports_tenant_created', ['tenant_id', 'created_at'], unique=False)

    op.create_table('ml_model_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('cohort', sa.String(length=100), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_event_count', sa.Integer(), nullable=False),
    sa.Column('training_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('score_threshold', sa.Float(), nullable=False),
    sa.Column('scored_event_count', sa.Integer(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'version', name='uq_ml_model_tenant_version')
    )
    with op.batch_alter_table('ml_model_versions', schema=None) as batch_op:
        batch_op.create_index('ix_ml_model_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('alert_id', sa.String(length=40), nullable=True),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_notifications_tenant_created', ['tenant_id', 'created_at'], unique=False)

    op.create_table('playbook_action_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbook_action_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbook_action_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_playbook_action_run', ['tenant_id', 'run_id', 'sequence'], unique=False)

    op.create_table('playbook_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=True),
    sa.Column('subject_id', sa.String(length=40), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('triggered_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.create_index('ix_playbook_runs_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbook_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_playbook_runs_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('playbooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('trigger_condition', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('replaced_by_id', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_refresh_tokens_user_active', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('rule_event_matches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('alert_id', sa.String(length=40), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'event_id', name='uq_rule_event_matches_rule_event')
    )
    with op.batch_alter_table('rule_event_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_event_matches_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_rule_event_matches_tenant_rule', ['tenant_id', 'rule_id'], unique=False)

    op.create_table('tenant_sso_configs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_env_var', sa.String(length=100), nullable=True),
    sa.Column('authorization_endpoint', sa.String(length=500), nullable=True),
    sa.Column('token_endpoint', sa.String(length=500), nullable=True),
    sa.Column('jwks_uri', sa.String(length=500), nullable=True),
    sa.Column('saml_metadata_url', sa.String(length=500), nullable=True),
    sa.Column('role_mapping', sa.JSON(), nullable=False),
    sa.Column('default_role', sa.String(length=20), nullable=False),
    sa.Column('jit_provisioning', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sso_required', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_sso_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_sso_configs_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('threat_feeds',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('api_key_env_var', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_confidence', sa.Integer(), nullable=False),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_status', sa.String(length=500), nullable=True),
    sa.Column('indicator_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_threat_feeds_tenant_slug')
    )
    with op.batch_alter_table('threat_feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_feeds_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('threat_indicators',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('value_normalized', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'indicator_type', 'value_normalized', name='uq_indicator_tenant_type_value')
    )
    with op.batch_alter_table('threat_indicators', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_expiry', ['tenant_id', 'expires_at'], unique=False)
        batch_op.create_index('ix_indicator_lookup', ['tenant_id', 'indicator_type', 'value_normalized', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_indicators_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detection_source', sa.String(length=20), nullable=False, server_default='rule'))
        batch_op.add_column(sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('dismissed_by_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('dismiss_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_alerts_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_alerts_tenant_status', ['tenant_id', 'status'], unique=False)

    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluation_window_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('match_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrichment', sa.JSON(), nullable=True))
        batch_op.create_index('ix_events_tenant_occurred', ['tenant_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_events_tenant_severity', ['tenant_id', 'severity_hint'], unique=False)
        batch_op.create_index('ix_events_tenant_source_ip', ['tenant_id', 'source_ip'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_usage_counters_tenant_period', ['tenant_id', 'period'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provisioned_by', sa.String(length=20), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('token_version')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('provisioned_by')

    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usage_counters_tenant_period', type_='unique')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('canceled_at')
        batch_op.drop_column('cancel_at_period_end')
        batch_op.drop_column('stripe_subscription_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_tenant_source_ip')
        batch_op.drop_index('ix_events_tenant_severity')
        batch_op.drop_index('ix_events_tenant_occurred')
        batch_op.drop_column('enrichment')

    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_column('match_count')
        batch_op.drop_column('last_matched_at')
        batch_op.drop_column('last_evaluated_at')
        batch_op.drop_column('evaluation_window_minutes')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_tenant_status')
        batch_op.drop_index('ix_alerts_tenant_created')
        batch_op.drop_column('notified_at')
        batch_op.drop_column('dismiss_reason')
        batch_op.drop_column('dismissed_by_user_id')
        batch_op.drop_column('dismissed_at')
        batch_op.drop_column('detection_source')

    with op.batch_alter_table('threat_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_indicators_tenant_id'))
        batch_op.drop_index('ix_indicator_lookup')
        batch_op.drop_index('ix_indicator_expiry')

    op.drop_table('threat_indicators')
    with op.batch_alter_table('threat_feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_feeds_tenant_id'))

    op.drop_table('threat_feeds')
    with op.batch_alter_table('tenant_sso_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_sso_configs_tenant_id'))

    op.drop_table('tenant_sso_configs')
    with op.batch_alter_table('rule_event_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_rule_event_matches_tenant_rule')
        batch_op.drop_index(batch_op.f('ix_rule_event_matches_tenant_id'))

    op.drop_table('rule_event_matches')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index('ix_refresh_tokens_user_active')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_tenant_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_tenant_id'))

    op.drop_table('playbooks')
    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_playbook_runs_tenant_status')
        batch_op.drop_index(batch_op.f('ix_playbook_runs_tenant_id'))
        batch_op.drop_index('ix_playbook_runs_tenant_created')

    op.drop_table('playbook_runs')
    with op.batch_alter_table('playbook_action_records', schema=None) as batch_op:
        batch_op.drop_index('ix_playbook_action_run')
        batch_op.drop_index(batch_op.f('ix_playbook_action_records_tenant_id'))

    op.drop_table('playbook_action_records')
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_tenant_created')
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_tenant_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('ml_model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_model_versions_tenant_id'))
        batch_op.drop_index('ix_ml_model_tenant_active')

    op.drop_table('ml_model_versions')
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_tenant_created')
        batch_op.drop_index(batch_op.f('ix_compliance_reports_tenant_id'))

    op.drop_table('compliance_reports')
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_created')
        batch_op.drop_index('ix_audit_tenant_action')
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_tenant_id'))

    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
